### ISSUE TITLE
🛠️ Todo: Add real separate micro frontends as apps

### ISSUE THREAD

**Issue by deleonio** [public-ui/lab-micro-frontends#4]
- [x] Angular, with KoliBri `v1`
- [x] React, with KoliBri `v2`
- [x] Vue, with KoliBri `v1`
- [x] One `index.html` loads all apps
